version: '3.9'

services:
  quarkus:
    image: akaka4ka/osmc-back-end:latest
    expose:
      - 8080

  db:
    image: postgres:14.2-alpine
    expose:
      - 5432

  nginx:
    image: akaka4ka/osmc-front-end:latest
    depends_on:
      - quarkus
    ports:
      - "80:80"
