name: CI

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Install graalvm
        uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '21.3.0.java11'
        
      - name: Install native-image
        run: gu install native-image
        
      - name: Build with Maven
        run: mvn package -Pnative
        
      - name: Docker build image
        run: docker build -t akaka4ka/osmc-back-end .
        
      - name: Publish docker image to Docker Hub
        run: docker push akaka4ka/osmc-back-end:latest
